{
 "title": "Heizung",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Außentemperatur",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "t_a" }
   ]
  },
  {
   "title": "Verlauf Außentemperatur",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "t_a" }
   ]
  },
  {
   "title": "Brenner",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heating" }
   ]
  },
  {
   "title": "Pumpe",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pumping" }
   ]
  },
  {
   "title": "Verlauf Vorlauf/Rücklauf",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "t_v", "legendFormat": "Vorlauftemperatur" },
    { "expr": "t_r", "legendFormat": "Rücklauftemperatur" }
   ]
  },
  {
   "title": "Brennerstarts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heater_starts" }
   ]
  },
  {
   "title": "Brennerlaufzeit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heater_runtime" }
   ]
  },
  {
   "title": "Vorlauftemperatur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "t_v" }
   ]
  },
  {
   "title": "Rücklauftemperatur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "t_r" }
   ]
  },
  {
   "title": "Rücklauf Solltemperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "t_r_soll" }
   ]
  }
 ]
}